#!/bin/bash

if [[ -z $LINUX ]]; then return; fi

sudo DEBIAN_FRONTEND=noninteractive apt-get install -yq --no-install-recommends \
    apt-transport-https \
    chromium-browser \
    cmake \
    curl \
    fd-find \
    fonts-powerline \
    fzf \
    gdb \
    gitk \
    less \
    python3 \
    python3-pip \
    shellcheck \
    silversearcher-ag \
    terminator \
    tmux \
    vim \
    wget \
    wmctrl \
    xdotool \
    zsh
gprint "apt install complete"
