#!/bin/bash

if [[ -z $LINUX ]]; then return; fi

sudo apt install -y --no-install-recommends \
    apt-transport-https \
    chromium-browser \
    cmake \
    curl \
    fonts-powerline \
    gdb \
    gitk \
    less \
    python3 \
    python3-pip \
    scons \
    shellcheck \
    silversearcher-ag \
    terminator \
    tmux \
    vim \
    wget \
    wmctrl \
    xdotool \
    zsh
gprint "apt install complete"