#!/bin/bash

if [[ -z $MAC ]]; then return; fi

brew install \
    bash-completion \
    fd \
    fzf \
    git \
    htop \
    jupyter \
    python3 \
    shellcheck \
    the_silver_searcher \
    tmux \
    tree \
    vim
