#!/bin/bash

if [[ -d ~/.oh-my-zsh ]]; then
    iprint "Oh my zsh directory already present; skipping."
else
    # Unattended install
    sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended

    # At this point, it seems likely that we'd want to switch to zsh as the default login shell:
    # local ZSH
    # ZSH=$(command -v zsh)
    # [[ -z $ZSH ]] && dprint "No zsh install found"
    # if grep -q "$ZSH" /etc/shells; then
    #     dprint "Adding your custom zsh at $ZSH to /etc/shells..."
    #     echo "$ZSH" | sudo tee -a /etc/shells
    # fi
    # if [[ $SHELL != "$ZSH" ]]; then
    #     dprint "Setting zsh as your default shell..."
    #     chsh -s "$ZSH"
    # fi
    # dprint "Installed oh-my-zsh"
fi

TARGET=$HOME/.zshrc
if [[ -f $TARGET ]]; then
    wprint "$TARGET found; making a backup at $TARGET.backup"
    mv "$TARGET" "$TARGET.backup"
fi
ln -sf "$DOTFILES/applications/zsh/.zshrc" "$TARGET"